# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tmx_statistics.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class TmxStatisticsUi(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(651, 501)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.btn_reset = QtWidgets.QPushButton(self.frame_3)
        self.btn_reset.setObjectName("btn_reset")
        self.horizontalLayout_3.addWidget(self.btn_reset)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lab_data = QtWidgets.QLabel(self.frame_2)
        self.lab_data.setText("")
        self.lab_data.setObjectName("lab_data")
        self.horizontalLayout_2.addWidget(self.lab_data)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.lab_progress = QtWidgets.QLabel(self.frame_2)
        self.lab_progress.setText("")
        self.lab_progress.setObjectName("lab_progress")
        self.horizontalLayout_2.addWidget(self.lab_progress)
        self.verticalLayout.addWidget(self.frame_2)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setAcceptDrops(False)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.widget)
        self.tableWidget.setAcceptDrops(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_export = QtWidgets.QPushButton(self.frame)
        self.btn_export.setEnabled(False)
        self.btn_export.setObjectName("btn_export")
        self.horizontalLayout.addWidget(self.btn_export)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.let_path = QtWidgets.QLineEdit(self.frame)
        self.let_path.setObjectName("let_path")
        self.horizontalLayout.addWidget(self.let_path)
        self.btn_path = QtWidgets.QPushButton(self.frame)
        self.btn_path.setObjectName("btn_path")
        self.horizontalLayout.addWidget(self.btn_path)
        self.btn_statistics = QtWidgets.QPushButton(self.frame)
        self.btn_statistics.setObjectName("btn_statistics")
        self.horizontalLayout.addWidget(self.btn_statistics)
        self.verticalLayout_2.addWidget(self.frame)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Tmx句对统计工具"))
        self.btn_reset.setText(_translate("Form", "重置"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "文件名"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "源语言"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "译后语言"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "句对数"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "文件路径"))
        self.btn_export.setText(_translate("Form", "导出excel"))
        self.btn_path.setText(_translate("Form", "选择文件夹"))
        self.btn_statistics.setText(_translate("Form", "开始统计"))
